### ISSUE TITLE
"npm install" needs a package.json file

### ISSUE THREAD

**Issue by zstauber** [phaserjs/discord-template#1]
Hello,
     Thank you all so much for this template.  I'm following along on the Phaser site, and now that I get to `npm install` it seems like it needs not only a package-lock.json file to run, but a package.json file, so it knows what to install for purposes of this template.  Barring that, can you tell me what packages I need to make my own package.json file?

     -Zack

**Comment by photonstorm** [comment]
You'll find those inside the `client` and `server` folders respectively, as they each need their own different set of libs.

Please follow our tutorial https://phaser.io/tutorials/creating-discord-games-with-phaser as it shows you what to do in this regard.

**Comment by zstauber** [comment]
Ah, thank you.  I see those now.  Sorry to bother.  This is what happens when I code late at night at my age.
