### ISSUE TITLE
zsh: command not found: cloudflared

### ISSUE THREAD

**Issue by ciaobotta** [phaserjs/discord-template#2]
I installed cloudflared locally and globally via npm, but once i get to the part of the tutorial where I type "cloudflared tunnel --url https://localhost:5173 ", it says cloudflared command isnt found. Anyone else have the same issue?

**Comment by candelibas** [comment]
It looks like a PATH issue, zsh not seeing global packages or installation failed somewhere.

Have you tried `npx cloudflared tunnel --url https://localhost:5173`?

You can also check if it's globally installed or not via: `npm list -g --depth=0`
