### ISSUE TITLE
fix: vite proxy api rewrite stripes away "api" path fragment

### ISSUE THREAD

**Issue by p4dd9** [phaserjs/discord-template#3]
in the current implementation the api path is removed in the vite proxy while the server.js have routes under /api/. currently if "/api/hellophaser" is proxied from the frontend, it will redirect to ":3001/hellophaser" instead of ":3001/api/hellophaser"

instead of this:
`rewrite: (path) => path.replace(/^\/.proxy\/api/, '')`
should be changed to this:
`rewrite: (path) => path.replace(/^\/\.proxy/, '')`

in the vite.config.js

Reproduce without discord env variables:
add
`app.get("/api/hellophaser", async (req, res) => {
  res.send({ msg: ":-)" });
});` to the server.js and try to access the endpoint via http://localhost:5173/.proxy/api/hellophaser should show 404

**Comment by candelibas** [comment]
Thanks, fixed!
